select *from customer limit 20
--Q.1What is the total revenue generated by
--Q.6 Which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--Q.7segment customers into new,returning,and loyal based on their total
--number of previous purchases,and slow the count of each segment
with customer_type as(
select customer_id,previous_purchases,
CASE 
   WHEN previous_purchases=1 THEN 'New'
   WHEN previous_purchases BETWEEN 2 AND 10 THEN'Returning'
   ELSE 'Loyal'
   END AS customer_segment
   from customer
)
select customer_segment,count(*) as"Number of customers"
from customer_type
group by customer_segment
--Q.8 What are the top 3 most purchased products within each category
with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders
ROW_NUMBER()over(partition by category order by count(customer_id)DESC)as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;