select *from customer limit 20
--Q.1What is the total revenue generated by male vs.female customer?
select gender,SUM(purchase_amount)as revenue
from customer
group by gender
--Q.2 Which customers used a discount but still spent more than the avg purchase amt.
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>= (select AVG(purchase_amount) from customer)
--q.3which are the top 5 products with highest avg review rating
select item_purchased,AVG(review_rating)as "Average product rating"
from customer 
group by item_purchased
order by AVG(review_rating) desc
limit 5
--Q.4 Compare the avg purchase amt between standard and express shipping
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by shipping_type
--Q.5Do subscribed customer spend more?compare avg. spend and total revenue
--between subscribers and non subscribers
select subscription_status,
COUNT(customer_id)as total_customers,
ROUND(AVG(purchase_amount),2)as avg_spend,
ROUND(AVG(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;